# Generated by Django 4.0.3 on 2022-03-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptId', models.IntegerField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('SSN', models.CharField(max_length=11)),
                ('addressStreet', models.CharField(max_length=100)),
                ('addressCity', models.CharField(max_length=50)),
                ('addressState', models.CharField(max_length=100)),
                ('addressPostal', models.CharField(max_length=10)),
                ('isManager', models.BooleanField()),
                ('employeeNum', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=15)),
                ('department', models.CharField(choices=[('1', 'Creative Services'), ('2', 'Product Development'), ('3', 'Marketing'), ('4', 'Strategic Planning'), ('5', 'Accounting'), ('6', 'Human Resources'), ('7', 'Quality Analysis')], max_length=25)),
                ('hireDate', models.DateField(max_length=25)),
            ],
        ),
    ]
